server:
  port: 8080

management:
  endpoint:
    metrics:
      enable: true
    info:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true

spring:
    datasource:
      url: jdbc:h2:mem:book_store_db
      username: sa
      password:
      driver-class-name: org.h2.Driver
      platform: h2
    h2:
      console:
        path: /console
        enabled: true
    jpa:
      hibernate:
        ddl-auto: create
      database-platform: org.hibernate.dialect.H2Dialect

logging.level.org.springframework.web: DEBUG
